apiVersion: v1
kind: Service
metadata:
  name: student-management-application
  namespace: devops
spec:
  selector:
    app: student-management-application
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: NodePort
